config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback' => 'sessions#create'

  get '/' => 'sessions#welcome'
  
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'

  resources :stories
  resources :stories, only: [:show] do
    resources :contributions, only: [:new, :index, :show]
  end

  resources :contributions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :stories
end

app/models/contribution.rb
class Contribution < ApplicationRecord
    belongs_to :user
    belongs_to :story

    validates :body, length: { in: 6..100 }

end

app/models/story.rb
class Story < ApplicationRecord
    has_many  :contributions
    has_many :users, through: :contributions
    belongs_to :category

    validates :hook, length: { maximum: 50 }
    validates :hook, presence: true

    scope :most_recent, -> {order('created_at DESC')}
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many  :contributions
    has_many :stories, through: :contributions

    validates :email, presence: true
    validates :email, uniqueness: true
    
    validates :bio, length: { maximum: 200 }

    def self.find_or_create_from_github(auth)
        user = User.find_or_create_by(email: auth['info']['email']) do |u|
            u.password = SecureRandom.hex(12)
            u.first_name = auth[:info][:email]
            u.email = auth[:info][:email]
        end
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?

    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_login
        unless logged_in?
            flash[:notify] = "User must be logged in to access this data."
            redirect_to login_path
        end
    end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController

    def index
      @contributions = Contribution.all
      # make method to do this
      @story = Story.find_by_id(params[:story_id])
      redirect_to @story
    end

    def new 
      @contribution = Contribution.new
      @story = Story.find_by_id(params[:story_id])
      @contributions = @story.contributions.all
    end

    def create
    @contribution = current_user.contributions.build(contribution_params)
      if !@contribution.save
        flash[:error] = "Contribution must be 6-100 characters."
      end
      redirect_to @contribution.story
    end
  
    private
  
    def contribution_params
      params.require(:contribution).permit(:body, :story_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        if auth 
            # user = User.find_or_create_by(email: auth['info']['email']) do |u|
            #     u.password = SecureRandom.hex(12)
            # end
            ##this line wass commented out v
            user = User.find_or_create_from_github(auth)
            if user.persisted?
                session[:user_id] = user.id
                redirect_to user_path(user)
            else
               
                redirect_to '/'
            end
        else
            @user = User.find_by(email: params[:email])
            if @user && @user.authenticate(params[:password])
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            else
                flash[:error] = "Invalid email or password."
                redirect_to login_path
            end
        end
    end

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    private

    def auth
      request.env['omniauth.auth']
    end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
    
    def index
        @stories = Story.most_recent
        if !logged_in?
            redirect_to '/'
        else
            @user = current_user
        end
    end

    def new 
        @story = Story.new
    end

    def create
        @story = current_user.stories.build(story_params)
        byebug
        if @story.save
          redirect_to @story
        else
          render '/stories/new'
        end
    end

    def show
        @story = Story.find_by_id(params[:id])
        @contributions = @story.contributions.all
        @contribution = Contribution.new
    end

    def edit 
        @story = Story.find(params[:id])
    end

    def update 
        @story = Story.find(params[:id])
        if @story.update(story_params)
            redirect_to @story
        else
            render :edit
        end
    end 

    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    private

    def story_params
        params.require(:story).permit(:hook)
    end

end

app/controllers/users_controller.rb
  class UsersController < ApplicationController

    def index
        redirect_to users_path
    end

    def new
        @user = User.new
    end

    def create
        if auth
            User.find_or_create_from_github(auth)
            binding.pry
        else
            @user = User.new(user_params)
            if @user.save
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            else
                render '/users/new'
            end
        end
    end

    def show
        if !logged_in?
            redirect_to '/'
        elsif
            @user = User.find_by(id: params[:id]) 
            @stories = @user.stories
        else
            @user = nil
            redirect_to '/'
        end
    end
     
    private
     
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :bio, :password, :password_confirmation)
    end

    def auth 
        request.env['omniauth.auth']
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contributions/new.html.erb
<%= link_to "Back to all Stories", stories_path, method: :get %>
<br><br>
<p>
  Started on <%= @story.created_at.strftime("%b %d, %Y") %> 
  
</p>

<div class="story">
  <h1><%= @story.hook %></h1>

  <h1>
      <% @contributions.each do |c| %>
          <%= c.body %>
      <% end %>
  </h1>
</div>

<%= render partial: "/shared/errors", locals: {object: @contributions} %>

<% flash.each do |type, msg| %>
    <div id="error_explanation">
        <%= msg %>
    </div>
<% end %>

<br>

<%= form_for @story.contributions.build do |f| %>
    <%= f.hidden_field :story_id, value: @story.id %>
    
    <p>
      <%= f.label :content, "Continue the story..." %><br><br>
      <%= f.text_area :body %>
    </p>
    
    <%= f.submit %>
  <% end %>

  <br>
  <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Story Chains</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="apple-touch-icon" href="http://example.com/images/apple-touch-icon.png" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <center><h1 class="logo m112">StoryChains</h1></center>
  
  <br>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

  <ul>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/stories/index.html.erb
<h1>Hey <%= link_to @user.email, user_path(@user) %> </h1>
<%= link_to "Log Out", logout_path, method: :delete %>
<br><br>
<a href="/stories/new">Create a New Story</a>

<h1>Story Chains</h1>
<ul>
  <% @stories.each do |story| %>
  <li><%= link_to story.hook, story_path(story) %> </li>
  <% end %>
</ul>

app/views/stories/new.html.erb
<%= link_to " < Back to All Stories", stories_path, method: :get %>
<br>

<h1>Start a New Story!</h1>

<h4> A hook (or narrative hook) is the literary technique of creating an enticing beginning—the very first line or opening of a story—designed to capture readers' interest. </h4>
<h4> Start your new story with a good hook: </h4>

<%= render partial: "/shared/errors", locals: {object: @story} %>

<%= form_for @story do |f| %>
  <%= f.text_field :hook %><br>
  <br />

  <%= f.submit %>
<% end %>

app/views/stories/show.html.erb
<%= link_to "< Back to all Stories", stories_path, method: :get %>
<br><br>
<p>
  Started on <%= @story.created_at.strftime("%b %d, %Y") %> 
  
</p>

<div class="story">
  <h1><%= @story.hook %></h1>

  <h1>
      <% @contributions.each do |c| %>
        <%= link_to c.body, user_path(c.user_id), method: :get %>
      <% end %>
  </h1>
</div>

<br><br>

<% flash.each do |type, msg| %>
  <div id="error_explanation">
      <%= msg %>
  </div>
  <br>
<% end %>

<%= form_for @story.contributions.build do |f| %>

    <%= f.hidden_field :story_id, value: @story.id %>
    
    <p>
      <%= f.label :content, "Continue the story..." %><br><br>
      <%= f.text_area :body %>
    </p>
    
    <%= f.submit %>
  <% end %>

  <br>
  <br>

app/views/users/new.html.erb
<h1>Sign up to create stories! </h1>

<%= render partial: "/shared/errors", locals: {object: @user} %>

<%= form_for @user do |f| %>

    First Name: <%= f.text_field :first_name %> <br>
    Last Name: <%= f.text_field :last_name %><br>
    Email: <%= f.text_field :email %><br>
    Bio: <%= f.text_area :bio %><br>
    Password: <%= f.password_field :password %><br>
    Password Confirmation: <%= f.password_field :password_confirmation %><br><br>
    <%= f.submit "Submit" %>
  <% end %>

app/views/users/show.html.erb
<h1><%= @user.email%>'s Story Chains </h1>
<h3><%= @user.first_name %> <%= @user.last_name %></h3>

<h3><%= @user.bio %> </h3>

<a href="/stories/new">Create a New Story</a><br>
<%= link_to "All Stories", stories_path, method: :get %>
<br><br>

<%= link_to "Log Out", logout_path, method: :delete %>

<br>

<h3> <%=@user.first_name%> has contributed to Story Chains
  <%= @user.contributions.count %>
    times: </h3>

<ul>
  <% @user.contributions.reverse.each do |c|%>
    <li>  <%= link_to c.story.hook, story_path(c.story) %> </li>
  <% end %>
</ul>